name: python-flask-confusion

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    ports:
      - "${PORT:-8000}:8000"
    networks: [lab]
    environment:
      DATABASE_URL: postgresql+psycopg://unsafe:code@db:5432/lab
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: unsafe
      POSTGRES_PASSWORD: code
      POSTGRES_DB: lab
    networks: [lab]
    # no volumes here, the database is ephemeral
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U unsafe -d lab -h localhost"]
      interval: 2s
      timeout: 3s
      retries: 30

  # Mailpit for email testing
  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: unless-stopped
    ports:
      # Web interface
      - 8025:8025
      # Note that we don't expose SMTP to the host, as it's only needed
      # within the docker compose network
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks: [lab]

networks:
  lab: {}
